name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SudoBank2/SudoBank2.csproj

    - name: Build
      run: dotnet build SudoBank2/SudoBank2.csproj --no-restore --configuration Release

    - name: Run tests
      run: dotnet test SudoBank2/SudoBank2.csproj --no-build --configuration Release --verbosity normal
